---
name: Test
on:
  pull_request:

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from
      # To avoid this issue we must specify numpy version
      - name: install xmlmerge
        run: |
          pip install xmlmerge
          pip install 'numpy<2'

      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Get changed directories using defaults
        id: changed-directories
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.51.1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.14.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tflint_config=$(pwd)/.tflint.hcl
          mkdir tflint_results
          # Adding this so that reviewdog doesn't fail when a single directory is modified
          # xmlmerge requires two or more xmlfiles
          echo "<checkstyle />" > tflint_results/empty.xml
          for dir in ${{ steps.changed-directories.outputs.all_changed_files }}; do
            mkdir -p tflint_results/$dir
            # Run TFLint and generate a report
            tflint -c $tflint_config --force -f=checkstyle --chdir $dir > "./tflint_results/$dir/result.xml"
          done
          # Merging all tflint checks into one xml file and run reviewdog against that xml file. This way we don't have to worry about reviewdog
          # overriding comments because the different files generated by tflint have different xml checks.
          find  ./tflint_results/ -type f -exec xmlmerge {} + | sed 's/severity="info"/severity="error"/g' >> results.xml
          cat results.xml | reviewdog -f=checkstyle -name="TFLint" -reporter=github-pr-check -level=warning
  formatter:
    name: Formatter
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: /tmp/.terraform/plugins
      TERRAFORM_VERSION: 1.2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Get changed directories using defaults
        id: changed-directories
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.14.1

      - name: Run test
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          for dir in ${{ steps.changed-directories.outputs.all_changed_files }}; do
            pushd $dir
            cat <<EOF > provider.ci.tf
            provider "aws" {
              alias = "this"
            }

            provider "aws" {
              alias = "peer"
            }

            provider "aws" {
              alias = "requester"
            }

            provider "aws" {
              alias = "accepter"
            }
          EOF
            terraform fmt -write=true provider.ci.tf
            terraform init
            terraform validate
            terraform fmt -check -recursive -diff .
            popd
          done
